### ISSUE TITLE
Request: officially supporting Python 3.12

### ISSUE THREAD

**Issue by jamesbraza** [krassowski/easy-entrez#25]
Hello team, love this package! Excited to start using it today, except, I use Python 3.12.

Any chance we can:
- Add Python 3.12 to the test matrix
- Add 3.12 to `setup.py`'s classifiers

Also, may be good to add `python_requires=">=3.7"` to the `setup()` call as well.

**Comment by krassowski** [comment]
Hello :wave: A pull requests doing so would be welcome!
