### ISSUE TITLE
Docs request: significance of `email`

### ISSUE THREAD

**Issue by jamesbraza** [krassowski/easy-entrez#28]
Can we add more details on the `email` parameter of `EntrezAPI`?

I found using `fake@hello.com` worked fine, my request went through.  Is `email` really a required part of the payload to send?

**Comment by krassowski** [comment]
This is documented in https://www.ncbi.nlm.nih.gov/books/NBK25497/.

**Comment by jamesbraza** [comment]
Fixed by https://github.com/krassowski/easy-entrez/pull/31
