### ISSUE TITLE
How can I obrain the SNP rs ids using CHR:POS_A1_A2 format for > 3K SNPs?

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [krassowski/easy-entrez#6]
I have a list of variants as follows and I would like to obtain rs ids using CHR:POS_A1_A2 format

1:26860336_C_T

**Comment by krassowski** [comment]
I am afraid Entrez API does not support fetching so many variants from unrelated regions at once. You would need to use a search query for each variant individually. If the region of interest is continuous (a range of coordinates on a single chromosome) you could try a range query demonstrated in [Obtaining amino acids change information for variants in given range](https://github.com/krassowski/easy-entrez#obtaining-amino-acids-change-information-for-variants-in-given-range) example.
